[package]
name = "jili"
license = "MIT"
version = "0.0.0"
description = "Quant lib"
repository = "https://github.com/aQuaYi/jili/"
authors = ["aQua <hi@aQuaYi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
